# Generated by Django 3.1.5 on 2021-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('R', 'Regular'), ('S', 'Square')], default='R', max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('toppings', models.CharField(max_length=20)),
            ],
        ),
    ]
